spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@localhost:27017/${MONGO_DATABASE:notification}?authSource=admin
      auto-index-creation: true
  rabbitmq:
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

notification:
  catalog:
    channels:
      EMAIL:
        providers:
          - simulated
        content-schema:
  provider:
    simulated:
      result: ACCEPTED
  rabbit:
    dispatch:
      exchange: notification.dispatch.exchange
      routing-key: notification.dispatch
      queue: notification.dispatch.queue
    events-exchange: notification.events.exchange
