spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification
      auto-index-creation: true

notification:
  catalog:
    channels:
      EMAIL:
        providers:
          - simulated
        content-schema:
  provider:
    simulated:
      result: ACCEPTED
  rabbit:
    dispatch:
      exchange: notification.dispatch.exchange
      routing-key: notification.dispatch
      queue: notification.dispatch.queue
    events-exchange: notification.events.exchange
