package co.edu.uco.notification.utils;

public enum ErrorCode {
  INVALID_CONTENT(1001, FailureCategory.PERMANENT_BUSINESS),
  INVALID_ATTACHMENT(1002, FailureCategory.PERMANENT_BUSINESS),
  CHANNEL_NOT_AVAILABLE(1003, FailureCategory.PERMANENT_BUSINESS),
  INVALID_REQUEST(1004, FailureCategory.PERMANENT_BUSINESS),
  REQUEST_BODY_TOO_LARGE(1005, FailureCategory.PERMANENT_BUSINESS),

  AUTHENTICATION_REQUIRED(2001, FailureCategory.PERMANENT_BUSINESS),
  INSUFFICIENT_ROLE(2002, FailureCategory.PERMANENT_BUSINESS),

  BUSINESS_ERROR(3000, FailureCategory.PERMANENT_BUSINESS),
  NOTIFICATION_NOT_FOUND(3001, FailureCategory.PERMANENT_BUSINESS),
  ATTACHMENT_UPLOAD_NOT_FOUND(3002, FailureCategory.PERMANENT_BUSINESS),
  ATTACHMENT_NOT_READY(3003, FailureCategory.PERMANENT_BUSINESS),
  ATTACHMENT_NOT_UPLOADED(3004, FailureCategory.PERMANENT_BUSINESS),
  ATTACHMENT_UPLOAD_EXPIRED(3005, FailureCategory.PERMANENT_BUSINESS),
  NOTIFICATION_VERSION_CONFLICT(3006, FailureCategory.PERMANENT_BUSINESS),
  NOTIFICATION_ALREADY_ACCEPTED(3007, FailureCategory.PERMANENT_BUSINESS),
  INVALID_STATUS_TRANSITION(3008, FailureCategory.PERMANENT_BUSINESS),
  ATTACHMENT_SCAN_MESSAGE_UNREADABLE(3010, FailureCategory.PERMANENT_BUSINESS),
  DISPATCH_MESSAGE_INVALID(3011, FailureCategory.PERMANENT_BUSINESS),
  NOTIFICATION_FAILED(3020, FailureCategory.PERMANENT_BUSINESS),
  NOTIFICATION_DISCARDED(3021, FailureCategory.PERMANENT_BUSINESS),
  UPDATE_EVENT_UNPARSEABLE(3030, FailureCategory.PERMANENT_BUSINESS),

  PROVIDER_ERROR(4000, FailureCategory.RECOVERABLE_PROVIDER),
  PROVIDER_RECOVERABLE_FAILURE(4002, FailureCategory.RECOVERABLE_PROVIDER),
  PROVIDER_REJECTED_BEFORE_CALL(4010, FailureCategory.PERMANENT_BUSINESS),
  PROVIDER_REJECTED_PERMANENT(4011, FailureCategory.PERMANENT_BUSINESS),
  PROVIDER_REJECTED_RECOVERABLE(4012, FailureCategory.RECOVERABLE_PROVIDER),
  PROVIDER_AUTHORIZATION_PERMANENT(4020, FailureCategory.PERMANENT_BUSINESS),
  PROVIDER_AUTHORIZATION_RECOVERABLE(4021, FailureCategory.RECOVERABLE_PROVIDER),

  INFRASTRUCTURE_ERROR(5000, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  ATTACHMENT_INSPECTION_UNAVAILABLE(5001, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  DISPATCH_RESERVATION_NOT_RELEASED(5002, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  DISPATCH_EVENTS_NOT_PUBLISHED(5003, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  REQUEUE_FAILED(5004, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  ENQUEUE_FAILED(5005, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  REQUEUE_PASS_FAILED(5006, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  DISPATCH_STUCK_IN_PROCESS_RELEASED(5007, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  ATTACHMENT_UPLOAD_NOT_FAILED(5010, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  MESSAGE_ATTEMPTS_EXHAUSTED(5020, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  MESSAGE_ATTEMPT_FAILED(5021, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  MESSAGE_REPUBLISH_FAILED(5022, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  DISPATCH_RESULT_NOT_PERSISTED(5030, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  ABANDONED_UPLOADS_SWEEP_FAILED(5040, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  PARAMETERS_UNAVAILABLE(5050, FailureCategory.RECOVERABLE_INFRASTRUCTURE),
  ATTACHMENT_OBJECT_DELETE_FAILED(5060, FailureCategory.RECOVERABLE_INFRASTRUCTURE);

  private static final String PREFIX = "NTF-";

  private final int number;
  private final FailureCategory category;

  ErrorCode(final int number, final FailureCategory category) {
    this.number = number;
    this.category = category;
  }

  public int number() {
    return number;
  }

  public String format() {
    return PREFIX + number;
  }

  public FailureCategory category() {
    return category;
  }

  public static ErrorCode genericFor(final FailureCategory category) {
    return switch (category) {
      case PERMANENT_BUSINESS -> BUSINESS_ERROR;
      case RECOVERABLE_PROVIDER -> PROVIDER_ERROR;
      case RECOVERABLE_INFRASTRUCTURE -> INFRASTRUCTURE_ERROR;
    };
  }
}
